"""initial schema

Revision ID: 7e10f5fc765b
Revises: 
Create Date: 2026-03-22 14:46:30.540816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e10f5fc765b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('tracking_id', sa.String(length=64), nullable=True))
    op.add_column('email_logs', sa.Column('opened_at', sa.DateTime(), nullable=True))
    op.add_column('email_logs', sa.Column('clicked_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_email_logs_tracking_id'), 'email_logs', ['tracking_id'], unique=True)
    op.create_foreign_key(None, 'email_logs', 'email_sequence_steps', ['sequence_step_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'email_logs', 'email_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    op.add_column('prospects', sa.Column('email_valid', sa.Boolean(), nullable=True))
    op.alter_column('prospects', 'score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('prospects', 'score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('prospects', 'email_valid')
    op.drop_constraint(None, 'email_logs', type_='foreignkey')
    op.drop_constraint(None, 'email_logs', type_='foreignkey')
    op.drop_index(op.f('ix_email_logs_tracking_id'), table_name='email_logs')
    op.drop_column('email_logs', 'clicked_at')
    op.drop_column('email_logs', 'opened_at')
    op.drop_column('email_logs', 'tracking_id')
    # ### end Alembic commands ###
